export const jobTitles = [
    { value: "ceo", label: "Prezes Zarządu" },
    { value: "cfo", label: "Dyrektor Finansowy" },
    { value: "cto", label: "Dyrektor Techniczny" },
    { value: "coo", label: "Dyrektor Operacyjny" },
    { value: "hr-manager", label: "Kierownik HR" },
    { value: "sales-manager", label: "Kierownik Sprzedaży" },
    { value: "marketing-specialist", label: "Specjalista do sp. marketingu" },
    { value: "accountant", label: "Księgowy" },
    { value: "assistant", label: "Asystent" },
    { value: "manager", label: "Manager" },
    { value: "coordinator", label: "Koordynator" },
    { value: "tinsmith", label: "Blacharz" },
    { value: "fitter", label: "Monter" },
];