export function getCountryMapper(value: string|null|undefined): string {
    switch (value) {
        case "Polska": return "Polska";
        case "POL": return "Polska";
        case "AFG": return "Afganistan";
        case "ALB": return "Albania";
        case "DZA": return "Algieria";
        case "AND": return "Andora";
        case "AGO": return "Angola";
        case "ATG": return "Antigua i Barbuda";
        case "SAU" : return "Arabia Saudyjska";
        case "ARG" : return "Argentyna";
        case "ARM" : return "Armenia";
        case "AUS" : return "Australia";
        case "AUT" : return "Austria";
        case "AZE" : return "Azerbejdżan";
        case "BHS" : return "Bahamy";
        case "BHR" : return "Bahrajn";
        case "BGD" : return "Bangladesz";
        case "BRB" : return "Barbados";
        case "BEL" : return "Belgia";
        case "BLZ" : return "Belize";
        case "BEN" : return "Benin";
        case "BTN" : return "Bhutan";
        case "BLR" : return "Białoruś";
        case "BOL": return "Boliwia";
        case "BIH": return "Bośnia i Hercegowina";
        case "BWA": return "Botswana";
        case "BRA": return "Brazylia";
        case "BRN": return "Brunei";
        case "BGR": return "Bułgaria";
        case "BFA": return "Burkina Faso";
        case "BDI": return "Burundi";
        case "CHL": return "Chile";
        case "CHN": return "Chiny";
        case "HRV": return "Chorwacja";
        case "CYP": return "Cypr";
        case "TCD": return "Czad";
        case "MNE": return "Czarnogóra";
        case "CZE": return "Czechy";
        case "DNK": return "Dania";
        case "COD": return "Demokratyczna Republika Konga";
        case "DMA": return "Dominika";
        case "DOM": return "Dominikana";
        case "ECU": return "Ekwador";
        case "EGY": return "Egipt";
        case "ERI": return "Erytrea";
        case "EST": return "Estonia";
        case "SWZ": return "Eswatini";
        case "ETH": return "Etiopia";
        case "FJI": return "Fidżi";
        case "PHL": return "Filipiny";
        case "FIN": return "Finlandia";
        case "FRA": return "Francja";
        case "GAB": return "Gabon";
        case "GMB": return "Gambia";
        case "GHA": return "Ghana";
        case "GRC": return "Grecja";
        case "GRD": return "Grenada";
        case "GEO": return "Gruzja";
        case "GTM": return "Gwatemala";
        case "GIN": return "Gwinea";
        case "GNB": return "Gwinea Bissau";
        case "GNQ": return "Gwinea Równikowa";
        case "HTI": return "Haiti";
        case "ESP": return "Hiszpania";
        case "NLD": return "Holandia";
        case "HND": return "Honduras";
        case "HKG": return "Hongkong";
        case "IND": return "Indie";
        case "IDN": return "Indonezja";
        case "IRQ": return "Irak";
        case "IRN": return "Iran";
        case "IRL": return "Irlandia";
        case "ISL": return "Islandia";
        case "ISR": return "Izrael";
        case "JAM": return "Jamajka";
        case "JPN": return "Japonia";
        case "YEM": return "Jemen";
        case "JOR": return "Jordania";
        case "KHM": return "Kambodża";
        case "CMR": return "Kamerun";
        case "CAN": return "Kanada";
        case "QAT": return "Katar";
        case "KAZ": return "Kazachstan";
        case "KEN": return "Kenia";
        case "KGZ": return "Kirgistan";
        case "KIR": return "Kiribati";
        case "COL": return "Kolumbia";
        case "COM": return "Komory";
        case "COG": return "Kongo";
        case "PRK": return "Korea Północna";
        case "KOR": return "Korea Południowa";
        case "CRI": return "Kostaryka";
        case "CUB": return "Kuba";
        case "KWT": return "Kuwejt";
        case "LAO": return "Laos";
        case "LSO": return "Lesotho";
        case "LBN": return "Liban";
        case "LBR": return "Liberia";
        case "LBY": return "Libia";
        case "LIE": return "Liechtenstein";
        case "LTU": return "Litwa";
        case "LUX": return "Luksemburg";
        case "LVA": return "Łotwa";
        case "MKD": return "Macedonia";
        case "MDG": return "Madagaskar";
        case "MWI": return "Malawi";
        case "MDV": return "Malediwy";
        case "MYS": return "Malezja";
        case "MLI": return "Mali";
        case "MLT": return "Malta";
        case "MAR": return "Maroko";
        case "MRT": return "Mauretania";
        case "MUS": return "Mauritius";
        case "MEX": return "Meksyk";
        case "FSM": return "Mikronezja";
        case "MDA": return "Mołdawia";
        case "MCO": return "Monako";
        case "MNG": return "Mongolia";
        case "MOZ": return "Mozambik";
        case "NAM": return "Namibia";
        case "NRU": return "Nauru";
        case "NPL": return "Nepal";
        case "DEU": return "Niemcy";
        case "NER": return "Niger";
        case "NGA": return "Nigeria";
        case "NIC": return "Nikaragua";
        case "NOR": return "Norwegia";
        case "NZL": return "Nowa Zelandia";
        case "OMN": return "Oman";
        case "PAK": return "Pakistan";
        case "PLW": return "Palau";
        case "PAN": return "Panama";
        case "PNG": return "Papua-Nowa Gwinea";
        case "PRY": return "Paragwaj";
        case "PER": return "Peru";
        case "PRT": return "Portugalia";
        case "ZAF": return "Republika Południowej Afryki";
        case "CAF": return "Republika Środkowoafrykańska";
        case "RUS": return "Rosja";
        case "ROU": return "Rumunia";
        case "RWA": return "Rwanda";
        case "KNA": return "Saint Kitts i Nevis";
        case "LCA": return "Saint Lucia";
        case "VCT": return "Saint Vincent i Grenadyny";
        case "SLV": return "Salwador";
        case "WSM": return "Samoa";
        case "SMR": return "San Marino";
        case "SEN": return "Senegal";
        case "SRB": return "Serbia";
        case "SYC": return "Seszele";
        case "SGP": return "Singapur";
        case "SLE": return "Sierra Leone";
        case "SVK": return "Słowacja";
        case "SVN": return "Słowenia";
        case "SOM": return "Somalia";
        case "LKA": return "Sri Lanka";
        case "USA": return "Stany Zjednoczone";
        case "SDN": return "Sudan";
        case "SSD": return "Sudan Południowy";
        case "SUR": return "Surinam";
        case "SYR": return "Syria";
        case "TJK": return "Tadżykistan";
        case "THA": return "Tajlandia";
        case "TZA": return "Tanzania";
        case "TLS": return "Timor Wschodni";
        case "TGO": return "Togo";
        case "TON": return "Tonga";
        case "TTO": return "Trynidad i Tobago";
        case "TUN": return "Tunezja";
        case "TUR": return "Turcja";
        case "TKM": return "Turkmenistan";
        case "TUV": return "Tuvalu";
        case "UGA": return "Uganda";
        case "UKR": return "Ukraina";
        case "URY": return "Urugwaj";
        case "UZB": return "Uzbekistan";
        case "VUT": return "Vanuatu";
        case "VAT": return "Watykan";
        case "VEN": return "Wenezuela";
        case "HUN": return "Węgry";
        case "GBR": return "Wielka Brytania";
        case "VNM": return "Wietnam";
        case "ITA": return "Włochy";
        case "CIV": return "Wybrzeże Kości Słoniowej";
        case "ZMB": return "Zambia";
        case "ZWE": return "Zimbabwe";
        case "ARE": return "Zjednoczone Emiraty Arabskie";
        default: return "Brak danych";
    }
}