import { Employee } from "../../utils/api-client/types/Employee.ts";

export const emptyEmployeeData: Employee = {
  _id: "",
  personalData: {
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    pesel: "",
    clothSize: "",
    nip: null,
    personalDataHistory: [],
    address1: {
      city1: "",
      house1: "",
      state1: "",
      street1: "",
      voivodeship1: "",
      zip1: "",
      address1History: [],
    },
    address2: {
      city2: "",
      house2: "",
      state2: "",
      street2: "",
      voivodeship2: "",
      zip2: "",
      address2History: [],
    },
  },
  jobDetails: {
    status: "",
    jobTitle: "",
    department: "",
    startDate: "",
    endDate: null,
    contractType: "",
    workSchedule: "",
    insuranceType: "",
    annualLeaveDays: 0,
    jobDetailsHistory: [],
    jobStayAddress: {
      street: "Brak danych",
      house: "Brak danych",
      city: "Brak danych",
      zip: "Brak danych",
      state: "Brak danych",
      voivodeship: "Brak danych",
      jobStayAddressHistory: [],
    },
    salary: {
      baseSalary: 0,
      currency: "",
      hourlyRate: 0,
      bankAccount: "",
      bankName: "",
      salaryHistory: [],
    },
  },
};
