export const countries = [
    { value: "POL", label: "Polska" },
    { value: "AFG", label: "Afganistan" },
    { value: "ALB", label: "Albania" },
    { value: "DZA", label: "Algieria" },
    { value: "AND", label: "Andora" },
    { value: "AGO", label: "Angola" },
    { value: "ATG", label: "Antigua i Barbuda" },
    { value: "SAU", label: "Arabia Saudyjska" },
    { value: "ARG", label: "Argentyna" },
    { value: "ARM", label: "Armenia" },
    { value: "AUS", label: "Australia" },
    { value: "AUT", label: "Austria" },
    { value: "AZE", label: "Azerbejdżan" },
    { value: "BHS", label: "Bahamy" },
    { value: "BHR", label: "Bahrajn" },
    { value: "BGD", label: "Bangladesz" },
    { value: "BRB", label: "Barbados" },
    { value: "BEL", label: "Belgia" },
    { value: "BLZ", label: "Belize" },
    { value: "BEN", label: "Benin" },
    { value: "BTN", label: "Bhutan" },
    { value: "BLR", label: "Białoruś" },
    { value: "BOL", label: "Boliwia" },
    { value: "BIH", label: "Bośnia i Hercegowina" },
    { value: "BWA", label: "Botswana" },
    { value: "BRA", label: "Brazylia" },
    { value: "BRN", label: "Brunei" },
    { value: "BGR", label: "Bułgaria" },
    { value: "BFA", label: "Burkina Faso" },
    { value: "BDI", label: "Burundi" },
    { value: "CHL", label: "Chile" },
    { value: "CHN", label: "Chiny" },
    { value: "HRV", label: "Chorwacja" },
    { value: "CYP", label: "Cypr" },
    { value: "TCD", label: "Czad" },
    { value: "MNE", label: "Czarnogóra" },
    { value: "CZE", label: "Czechy" },
    { value: "DNK", label: "Dania" },
    { value: "COD", label: "Demokratyczna Republika Konga" },
    { value: "DMA", label: "Dominika" },
    { value: "DOM", label: "Dominikana" },
    { value: "ECU", label: "Ekwador" },
    { value: "EGY", label: "Egipt" },
    { value: "ERI", label: "Erytrea" },
    { value: "EST", label: "Estonia" },
    { value: "SWZ", label: "Eswatini" },
    { value: "ETH", label: "Etiopia" },
    { value: "FJI", label: "Fidżi" },
    { value: "PHL", label: "Filipiny" },
    { value: "FIN", label: "Finlandia" },
    { value: "FRA", label: "Francja" },
    { value: "GAB", label: "Gabon" },
    { value: "GMB", label: "Gambia" },
    { value: "GHA", label: "Ghana" },
    { value: "GRC", label: "Grecja" },
    { value: "GRD", label: "Grenada" },
    { value: "GEO", label: "Gruzja" },
    { value: "GTM", label: "Guatemala" },
    { value: "GIN", label: "Guinea" },
    { value: "GNB", label: "Gwinea Bissau" },
    { value: "GNQ", label: "Gwinea Równikowa" },
    { value: "HTI", label: "Haiti" },
    { value: "ESP", label: "Hiszpania" },
    { value: "NLD", label: "Holandia" },
    { value: "HND", label: "Honduras" },
    { value: "HKG", label: "Hongkong" },
    { value: "IND", label: "Indie" },
    { value: "IDN", label: "Indonezja" },
    { value: "IRQ", label: "Irak" },
    { value: "IRN", label: "Iran" },
    { value: "IRL", label: "Irlandia" },
    { value: "ISL", label: "Islandia" },
    { value: "ISR", label: "Izrael" },
    { value: "JAM", label: "Jamajka" },
    { value: "JPN", label: "Japonia" },
    { value: "YEM", label: "Jemen" },
    { value: "JOR", label: "Jordania" },
    { value: "KHM", label: "Kambodża" },
    { value: "CMR", label: "Kamerun" },
    { value: "CAN", label: "Kanada" },
    { value: "QAT", label: "Katar" },
    { value: "KAZ", label: "Kazachstan" },
    { value: "KEN", label: "Kenia" },
    { value: "KGZ", label: "Kirgistan" },
    { value: "KIR", label: "Kiribati" },
    { value: "COL", label: "Kolumbia" },
    { value: "COM", label: "Komory" },
    { value: "COG", label: "Kongo" },
    { value: "KOR", label: "Korea Południowa" },
    { value: "PRK", label: "Korea Północna" },
    { value: "CRI", label: "Kostaryka" },
    { value: "CUB", label: "Kuba" },
    { value: "KWT", label: "Kuwejt" },
    { value: "LAO", label: "Laos" },
    { value: "LSO", label: "Lesotho" },
    { value: "LBN", label: "Liban" },
    { value: "LBR", label: "Liberia" },
    { value: "LBY", label: "Libia" },
    { value: "LIE", label: "Liechtenstein" },
    { value: "LTU", label: "Litwa" },
    { value: "LUX", label: "Luksemburg" },
    { value: "LVA", label: "Łotwa" },
    { value: "MKD", label: "Macedonia Północna" },
    { value: "MDG", label: "Madagaskar" },
    { value: "MWI", label: "Malawi" },
    { value: "MDV", label: "Malediwy" },
    { value: "MYS", label: "Malezja" },
    { value: "MLI", label: "Mali" },
    { value: "MLT", label: "Malta" },
    { value: "MAR", label: "Maroko" },
    { value: "MRT", label: "Mauretania" },
    { value: "MUS", label: "Mauritius" },
    { value: "MEX", label: "Meksyk" },
    { value: "FSM", label: "Mikronezja" },
    { value: "MDA", label: "Mołdawia" },
    { value: "MCO", label: "Monako" },
    { value: "MNG", label: "Mongolia" },
    { value: "MOZ", label: "Mozambik" },
    { value: "NAM", label: "Namibia" },
    { value: "NRU", label: "Nauru" },
    { value: "NPL", label: "Nepal" },
    { value: "DEU", label: "Niemcy" },
    { value: "NER", label: "Niger" },
    { value: "NGA", label: "Nigeria" },
    { value: "NIC", label: "Nikaragua" },
    { value: "NOR", label: "Norwegia" },
    { value: "NZL", label: "Nowa Zelandia" },
    { value: "OMN", label: "Oman" },
    { value: "PAK", label: "Pakistan" },
    { value: "PLW", label: "Palau" },
    { value: "PAN", label: "Panama" },
    { value: "PNG", label: "Papua-Nowa Gwinea" },
    { value: "PRY", label: "Paragwaj" },
    { value: "PER", label: "Peru" },
    { value: "PRT", label: "Portugalia" },
    { value: "ZAF", label: "Republika Południowej Afryki" },
    { value: "CAF", label: "Republika Środkowoafrykańska" },
    { value: "RUS", label: "Rosja" },
    { value: "ROU", label: "Rumunia" },
    { value: "RWA", label: "Rwanda" },
    { value: "KNA", label: "Saint Kitts i Nevis" },
    { value: "LCA", label: "Saint Lucia" },
    { value: "VCT", label: "Saint Vincent i Grenadyny" },
    { value: "SLV", label: "Salwador" },
    { value: "WSM", label: "Samoa" },
    { value: "SMR", label: "San Marino" },
    { value: "SEN", label: "Senegal" },
    { value: "SRB", label: "Serbia" },
    { value: "SYC", label: "Seszele" },
    { value: "SGP", label: "Singapur" },
    { value: "SLE", label: "Sierra Leone" },
    { value: "SVK", label: "Słowacja" },
    { value: "SVN", label: "Słowenia" },
    { value: "SOM", label: "Somalia" },
    { value: "LKA", label: "Sri Lanka" },
    { value: "USA", label: "Stany Zjednoczone" },
    { value: "SDN", label: "Sudan" },
    { value: "SSD", label: "Sudan Południowy" },
    { value: "SUR", label: "Surinam" },
    { value: "SYR", label: "Syria" },
    { value: "TJK", label: "Tadżykistan" },
    { value: "THA", label: "Tajlandia" },
    { value: "TZA", label: "Tanzania" },
    { value: "TLS", label: "Timor Wschodni" },
    { value: "TGO", label: "Togo" },
    { value: "TON", label: "Tonga" },
    { value: "TTO", label: "Trynidad i Tobago" },
    { value: "TUN", label: "Tunezja" },
    { value: "TUR", label: "Turcja" },
    { value: "TKM", label: "Turkmenistan" },
    { value: "TUV", label: "Tuvalu" },
    { value: "UGA", label: "Uganda" },
    { value: "UKR", label: "Ukraina" },
    { value: "URY", label: "Urugwaj" },
    { value: "UZB", label: "Uzbekistan" },
    { value: "VUT", label: "Vanuatu" },
    { value: "VAT", label: "Watykan" },
    { value: "VEN", label: "Wenezuela" },
    { value: "HUN", label: "Węgry" },
    { value: "GBR", label: "Wielka Brytania" },
    { value: "VNM", label: "Wietnam" },
    { value: "ITA", label: "Włochy" },
    { value: "CIV", label: "Wybrzeże Kości Słoniowej" },
    { value: "ZMB", label: "Zambia" },
    { value: "ZWE", label: "Zimbabwe" },
    { value: "ARE", label: "Zjednoczone Emiraty Arabskie" },
];