name: Deploy

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: production

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read  # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"
        env:
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_SUBTITLE: ${{ secrets.APP_SUBTITLE }}
          API_URL: ${{ secrets.API_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          AUTH_PROJECT_ID: ${{ secrets.AUTH_PROJECT_ID }}
          AUTH_ENDPOINT: ${{ secrets.AUTH_ENDPOINT }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "merit-app"
          entrypoint: "main.ts"
          root: "."
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_SUBTITLE: ${{ secrets.APP_SUBTITLE }}
          API_URL: ${{ secrets.API_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          AUTH_PROJECT_ID: ${{ secrets.AUTH_PROJECT_ID }}
          AUTH_ENDPOINT: ${{ secrets.AUTH_ENDPOINT }}
